package es.dominion.curso.negocio.entidades;
// Generated 01-may-2016 23:51:49 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistroUsuarios generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO_USUARIOS", catalog="MASTER")
public class RegistroUsuarios implements java.io.Serializable {

	private Long codigoRegistro;
	private String codigoUsuario;
	private Date fechaEntrada;
	private Date fechaSalida;
	private String duracion;
	private Short ficherosSubidos;
	private BigDecimal informacionSubida;

	public RegistroUsuarios() {
	}

	public RegistroUsuarios(Long codigoRegistro, String codigoUsuario, Date fechaEntrada) {
		this.codigoRegistro = codigoRegistro;
		this.codigoUsuario = codigoUsuario;
		this.fechaEntrada = fechaEntrada;
	}

	public RegistroUsuarios(Long codigoRegistro, String codigoUsuario, Date fechaEntrada, Date fechaSalida,
			String duracion, Short ficherosSubidos, BigDecimal informacionSubida) {
		this.codigoRegistro = codigoRegistro;
		this.codigoUsuario = codigoUsuario;
		this.fechaEntrada = fechaEntrada;
		this.fechaSalida = fechaSalida;
		this.duracion = duracion;
		this.ficherosSubidos = ficherosSubidos;
		this.informacionSubida = informacionSubida;
	}

	@Id

	@Column(name = "CODIGO_REGISTRO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigoRegistro() {
		return this.codigoRegistro;
	}

	public void setCodigoRegistro(Long codigoRegistro) {
		this.codigoRegistro = codigoRegistro;
	}

	@Column(name = "CODIGO_USUARIO", nullable = false, length = 20)
	public String getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(String codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_ENTRADA", nullable = false, length = 7)
	public Date getFechaEntrada() {
		return this.fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_SALIDA", length = 7)
	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	@Column(name = "DURACION", length = 50)
	public String getDuracion() {
		return this.duracion;
	}

	public void setDuracion(String duracion) {
		this.duracion = duracion;
	}

	@Column(name = "FICHEROS_SUBIDOS", precision = 3, scale = 0)
	public Short getFicherosSubidos() {
		return this.ficherosSubidos;
	}

	public void setFicherosSubidos(Short ficherosSubidos) {
		this.ficherosSubidos = ficherosSubidos;
	}

	@Column(name = "INFORMACION_SUBIDA", precision = 15)
	public BigDecimal getInformacionSubida() {
		return this.informacionSubida;
	}

	public void setInformacionSubida(BigDecimal informacionSubida) {
		this.informacionSubida = informacionSubida;
	}

}
