package es.dominion.curso.negocio.entidades;
// Generated 01-may-2016 23:51:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "ROLES", catalog="MASTER")
public class Roles implements java.io.Serializable {

	private Byte codigoRol;
	private String descripcionRol;
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
	private Set<Tareas> tareases = new HashSet<Tareas>(0);

	public Roles() {
	}

	public Roles(Byte codigoRol) {
		this.codigoRol = codigoRol;
	}

	public Roles(Byte codigoRol, String descripcionRol, Set<Usuarios> usuarioses, Set<Tareas> tareases) {
		this.codigoRol = codigoRol;
		this.descripcionRol = descripcionRol;
		this.usuarioses = usuarioses;
		this.tareases = tareases;
	}

	@Id

	@Column(name = "CODIGO_ROL", unique = true, nullable = false, precision = 2, scale = 0)
	public Byte getCodigoRol() {
		return this.codigoRol;
	}

	public void setCodigoRol(Byte codigoRol) {
		this.codigoRol = codigoRol;
	}

	@Column(name = "DESCRIPCION_ROL", length = 100)
	public String getDescripcionRol() {
		return this.descripcionRol;
	}

	public void setDescripcionRol(String descripcionRol) {
		this.descripcionRol = descripcionRol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ROLES_TAREAS", joinColumns = {
			@JoinColumn(name = "CODIGO_ROL", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CODIGO_TAREA", nullable = false, updatable = false) })
	public Set<Tareas> getTareases() {
		return this.tareases;
	}

	public void setTareases(Set<Tareas> tareases) {
		this.tareases = tareases;
	}

}
