package es.dominion.curso.negocio.entidades;
// Generated 01-may-2016 23:51:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TareasUsuarios generated by hbm2java
 */
@Entity
@Table(name = "TAREAS_USUARIOS", catalog="MASTER")
public class TareasUsuarios implements java.io.Serializable {

	private Long codigoTareausuario;
	private String descripcionTareausuario;
	private String estadoTarea;
	private Set<TareasRealizadas> tareasRealizadases = new HashSet<TareasRealizadas>(0);

	public TareasUsuarios() {
	}

	public TareasUsuarios(Long codigoTareausuario) {
		this.codigoTareausuario = codigoTareausuario;
	}

	public TareasUsuarios(Long codigoTareausuario, String descripcionTareausuario, String estadoTarea,
			Set<TareasRealizadas> tareasRealizadases) {
		this.codigoTareausuario = codigoTareausuario;
		this.descripcionTareausuario = descripcionTareausuario;
		this.estadoTarea = estadoTarea;
		this.tareasRealizadases = tareasRealizadases;
	}

	@Id

	@Column(name = "CODIGO_TAREAUSUARIO", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigoTareausuario() {
		return this.codigoTareausuario;
	}

	public void setCodigoTareausuario(Long codigoTareausuario) {
		this.codigoTareausuario = codigoTareausuario;
	}

	@Column(name = "DESCRIPCION_TAREAUSUARIO", length = 150)
	public String getDescripcionTareausuario() {
		return this.descripcionTareausuario;
	}

	public void setDescripcionTareausuario(String descripcionTareausuario) {
		this.descripcionTareausuario = descripcionTareausuario;
	}

	@Column(name = "ESTADO_TAREA", length = 2)
	public String getEstadoTarea() {
		return this.estadoTarea;
	}

	public void setEstadoTarea(String estadoTarea) {
		this.estadoTarea = estadoTarea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tareasUsuarios")
	public Set<TareasRealizadas> getTareasRealizadases() {
		return this.tareasRealizadases;
	}

	public void setTareasRealizadases(Set<TareasRealizadas> tareasRealizadases) {
		this.tareasRealizadases = tareasRealizadases;
	}

}
