package es.dominion.curso.negocio.entidades;
// Generated 01-may-2016 23:51:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tareas generated by hbm2java
 */
@Entity
@Table(name = "TAREAS", catalog="MASTER")
public class Tareas implements java.io.Serializable {

	private Byte codigoTarea;
	private String descripcionTarea;
	private String vinculo;
	private Set<Roles> roleses = new HashSet<Roles>(0);

	public Tareas() {
	}

	public Tareas(Byte codigoTarea) {
		this.codigoTarea = codigoTarea;
	}

	public Tareas(Byte codigoTarea, String descripcionTarea, String vinculo, Set<Roles> roleses) {
		this.codigoTarea = codigoTarea;
		this.descripcionTarea = descripcionTarea;
		this.vinculo = vinculo;
		this.roleses = roleses;
	}

	@Id

	@Column(name = "CODIGO_TAREA", unique = true, nullable = false, precision = 2, scale = 0)
	public Byte getCodigoTarea() {
		return this.codigoTarea;
	}

	public void setCodigoTarea(Byte codigoTarea) {
		this.codigoTarea = codigoTarea;
	}

	@Column(name = "DESCRIPCION_TAREA", length = 2000)
	public String getDescripcionTarea() {
		return this.descripcionTarea;
	}

	public void setDescripcionTarea(String descripcionTarea) {
		this.descripcionTarea = descripcionTarea;
	}

	@Column(name = "VINCULO", length = 50)
	public String getVinculo() {
		return this.vinculo;
	}

	public void setVinculo(String vinculo) {
		this.vinculo = vinculo;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tareases")
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

}
