package es.dominion.curso.negocio.entidades;
// Generated 01-may-2016 23:51:49 by Hibernate Tools 4.3.1.Final

import java.sql.Blob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TareasRealizadas generated by hbm2java
 */
@Entity
@Table(name = "TAREAS_REALIZADAS", catalog="MASTER")
public class TareasRealizadas implements java.io.Serializable {

	private Long codigoTarearealizada;
	private TareasUsuarios tareasUsuarios;
	private String usuario;
	private Date fechaRealizacion;
	private Blob datosAñadidos;
	private Blob datosModificados;
	private Blob datosEliminados;

	public TareasRealizadas() {
	}

	public TareasRealizadas(Long codigoTarearealizada, String usuario) {
		this.codigoTarearealizada = codigoTarearealizada;
		this.usuario = usuario;
	}

	public TareasRealizadas(Long codigoTarearealizada, TareasUsuarios tareasUsuarios, String usuario,
			Date fechaRealizacion, Blob datosAñadidos, Blob datosModificados, Blob datosEliminados) {
		this.codigoTarearealizada = codigoTarearealizada;
		this.tareasUsuarios = tareasUsuarios;
		this.usuario = usuario;
		this.fechaRealizacion = fechaRealizacion;
		this.datosAñadidos = datosAñadidos;
		this.datosModificados = datosModificados;
		this.datosEliminados = datosEliminados;
	}

	@Id

	@Column(name = "CODIGO_TAREAREALIZADA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getCodigoTarearealizada() {
		return this.codigoTarearealizada;
	}

	public void setCodigoTarearealizada(Long codigoTarearealizada) {
		this.codigoTarearealizada = codigoTarearealizada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_TAREAUSUARIO")
	public TareasUsuarios getTareasUsuarios() {
		return this.tareasUsuarios;
	}

	public void setTareasUsuarios(TareasUsuarios tareasUsuarios) {
		this.tareasUsuarios = tareasUsuarios;
	}

	@Column(name = "USUARIO", nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REALIZACION", length = 7)
	public Date getFechaRealizacion() {
		return this.fechaRealizacion;
	}

	public void setFechaRealizacion(Date fechaRealizacion) {
		this.fechaRealizacion = fechaRealizacion;
	}

	@Column(name = "DATOS_AÑADIDOS")
	public Blob getDatosAñadidos() {
		return this.datosAñadidos;
	}

	public void setDatosAñadidos(Blob datosAñadidos) {
		this.datosAñadidos = datosAñadidos;
	}

	@Column(name = "DATOS_MODIFICADOS")
	public Blob getDatosModificados() {
		return this.datosModificados;
	}

	public void setDatosModificados(Blob datosModificados) {
		this.datosModificados = datosModificados;
	}

	@Column(name = "DATOS_ELIMINADOS")
	public Blob getDatosEliminados() {
		return this.datosEliminados;
	}

	public void setDatosEliminados(Blob datosEliminados) {
		this.datosEliminados = datosEliminados;
	}

}
